version: '3.8'
services:
  web:
    build:
      context: ./
    image: backend-qa:latest
    container_name: web
    hostname: web
    volumes:
    - ./:/usr/src/app
    ports:
      - 8010:8000
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: populate
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
      APP_NAME: web
      AWS_REGION_NAME:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_BUCKET:
      POD_TYPE: web
    restart: always
    networks:
      - streamlit

networks:
  streamlit:
    name: qa-network
    external: true
