"""create inital table

Revision ID: 6f4929d78150
Revises: 
Create Date: 2023-11-12 18:55:34.282170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f4929d78150'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('TagID', sa.Integer(), nullable=False),
    sa.Column('TagName', sa.String(length=50), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('TagID'),
    sa.UniqueConstraint('TagName')
    )
    op.create_table('users',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('UserID')
    )
    op.create_table('questions',
    sa.Column('QuestionID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('QuestionText', sa.String(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['users.UserID'], ),
    sa.PrimaryKeyConstraint('QuestionID'),
    sa.UniqueConstraint('QuestionText')
    )
    op.create_table('answers',
    sa.Column('AnswerID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('QuestionID', sa.Integer(), nullable=False),
    sa.Column('AnswerText', sa.String(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['QuestionID'], ['questions.QuestionID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['users.UserID'], ),
    sa.PrimaryKeyConstraint('AnswerID'),
    sa.UniqueConstraint('AnswerText')
    )
    op.create_table('question_tags',
    sa.Column('QuestionID', sa.Integer(), nullable=True),
    sa.Column('TagID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['QuestionID'], ['questions.QuestionID'], ),
    sa.ForeignKeyConstraint(['TagID'], ['tags.TagID'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_tags')
    op.drop_table('answers')
    op.drop_table('questions')
    op.drop_table('users')
    op.drop_table('tags')
    # ### end Alembic commands ###
